server:
  port: 8888

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.154.136:3306/mblog?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  redis:
    host: 192.168.154.136
    password: 123456
    port: 6379
    database: 1
    connect-timeout: 10000

logging:
  level:
    root: info

token:
  # 1000 * 60 * 60 * 24 * 3
  expire-time: 259200000
  secret-key: lzqKmZQF3skdr2wzx7x9xfQD
